server:
 port: 8092
 
spring:
  mvc: 
   view: 
    prefix: classpath:/templates/
    suffix: .html
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    username: zyz
    password: "!QAZ2wsx"
    url: jdbc:mysql://rm-2ze6zmfoar7ni3mso3o.mysql.rds.aliyuncs.com:3306/springstudy?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 39.107.56.25
#    port: 16379
#    password: "!QAZ2wsx"
 
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: sppringBootStudy001.com.model
 
bean001:
 name: ZYZ
 age: 5
 lovers: 
 subject:
  - java
  - c
 
sayMe: "u am i now"

logging:
 level:
  sppringBootStudy001.com.dao: debug